<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    </PropertyGroup>

    <PropertyGroup>
        <UseWindowsToolset>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))</UseWindowsToolset>
        <UseMacOSToolset>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))</UseMacOSToolset>
        <UseLinuxToolset>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))</UseLinuxToolset>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Vezel.Zig.Toolsets.win-x64" Version="0.15.1.1" Condition="'$(UseWindowsToolset)' == 'true'">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Vezel.Zig.Toolsets.osx-x64" Version="0.15.1.1" Condition="'$(UseMacOSToolset)' == 'true'">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Vezel.Zig.Toolsets.linux-x64" Version="0.15.1.1" Condition="'$(UseLinuxToolset)' == 'true'">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <PropertyGroup>
        <OutputRoot>out\$(Configuration)</OutputRoot>
        <ExportRoot>..\Jolt.Native\$(Configuration)</ExportRoot>
    </PropertyGroup>

    <PropertyGroup>
        <NativeOptimize>Debug</NativeOptimize>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <NativeOptimize>ReleaseFast</NativeOptimize>
    </PropertyGroup>

    <ItemGroup>
        <!-- x86 -->
        <NativePlatform Include="x86_64-windows"  CopySourceFiles="bin\*.dll"/>
        <NativePlatform Include="x86_64-macos"    CopySourceFiles="lib\*.dylib"/>
        <NativePlatform Include="x86_64-linux"    CopySourceFiles="lib\*.so"/>
        <!-- aarch64 -->
        <NativePlatform Include="aarch64-windows" CopySourceFiles="bin\*.dll"/>
        <NativePlatform Include="aarch64-macos"   CopySourceFiles="lib\*.dylib"/>
        <!-- aarch64-linux is only available to unity enterprise clients, no way to verify -->
    </ItemGroup>

    <Target Name="Compile Jolt" AfterTargets="Build" Condition="'$(ZigExePath)' != ''">
        <!-- clean prior outputs -->
        <RemoveDir Directories="out/$(Configuration)" />
        <!-- produce single and double precision outputs for each platform -->
        <Exec Command="$(ZigExePath) build --summary all --prefix $(OutputRoot)\%(NativePlatform.Identity) -Dtarget=%(NativePlatform.Identity) -Doptimize=$(NativeOptimize)"/>
        <Exec Command="$(ZigExePath) build --summary all --prefix $(OutputRoot)\%(NativePlatform.Identity) -Dtarget=%(NativePlatform.Identity) -Doptimize=$(NativeOptimize) -Duse_double_precision=true"/>
    </Target>

    <Target Name="Export Jolt" AfterTargets="Compile Jolt" Outputs="%(NativePlatform.Identity)">
        <ItemGroup>
            <NativePlatformFiles Include="$(OutputRoot)\%(NativePlatform.Identity)\%(NativePlatform.CopySourceFiles)"/>
        </ItemGroup>
        <Copy SourceFiles="@(NativePlatformFiles)" DestinationFolder="$(ExportRoot)\%(NativePlatform.Identity)"/>
    </Target>

    <Target Name="Generate Jolt Bindings" AfterTargets="Build">
        <PropertyGroup>
            <OutputFile>..\Jolt\Bindings\UnsafeBindings.g.cs</OutputFile>
        </PropertyGroup>
        <!-- generate unsafe bindings from clangsharppinvokegenerator -->
        <Exec Command="clangsharppinvokegenerator --include-directory &quot;$(ZigToolsetPath)lib\include&quot; -f lib\joltc\joltc.h -n Jolt -m UnsafeBindings -l joltc -o $(OutputFile) @clangsharp.rsp"/>
        <!-- replace inlined lib name with constant so we can substitute lib name for double precision -->
        <WriteLinesToFile File="$(OutputFile)" Lines="$([System.IO.File]::ReadAllText($(OutputFile)).Replace('&quot;joltc&quot;','JOLT_LIB'))" Overwrite="true" />
    </Target>

</Project>